AWSTemplateFormatVersion: 2010-09-09
Description: Ingest data from WMATA's GTFS endpoint

Parameters:
    IngestedDataS3Bucket:
        Type: String
        Description: Name of S3 bucket to which data will be written

    IngestedDataS3Prefix:
        Type: String
        Description: Prefix within S3 bucket to which data will be written; must end in '/'
        AllowedPattern: '[0-9a-z\-\.\/]+\/'
        Default: 'testing/'

    GTFSVehiclePositionURL:
        Type: String
        Description: URL for GTFS vehicle positions
        Default: https://api.wmata.com/gtfs/rail-gtfsrt-vehiclepositions.pb

    APIKeyParameterARN:
        Type: String
        Description: ARN of SSM Parameter with API key

    PythonRuntime:
        Type: String
        Default: python3.8

Resources:

    PythonDependenciesLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            CompatibleRuntimes:
                - !Ref PythonRuntime
            Content: ./src/layer

    PollerFunctionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                        Service: lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Policies:
                - PolicyName: additional-permissions
                  PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                        - Effect: Allow
                          Action: ssm:GetParameter
                          Resource: !Ref APIKeyParameterARN
                        - Effect: Allow
                          Action: s3:PutObject
                          Resource: !Sub "arn:aws:s3:::${IngestedDataS3Bucket}/${IngestedDataS3Prefix}*"

    PollerFunction:
        Type: AWS::Lambda::Function
        Properties:
            Code: ./src/poller-function
            Environment:
                Variables:
                    GTFS_VEHICLE_POSITION_URL: !Ref GTFSVehiclePositionURL
                    INGESTED_DATA_S3_BUCKET: !Ref IngestedDataS3Bucket
                    INGESTED_DATA_S3_PREFIX: !Ref IngestedDataS3Prefix
                    API_KEY_PARAMETER_ARN: !Ref APIKeyParameterARN
            Handler: lambda_function.lambda_handler
            Layers:
                - !Ref PythonDependenciesLayer
            Role: !GetAtt PollerFunctionRole.Arn
            Runtime: !Ref PythonRuntime
            Timeout: 30




